Repository DO-NOTTO-DO/AOS-NOTTODO, pull requests merged in 2023-07, with the labels that each got.

#121 Feat/118 snackbar custom
  app/src/main/java/kr/co/nottodo/util/ContextExtension.kt
  app/src/main/java/kr/co/nottodo/view/snackbar/NotTodoSnackbar.kt
  app/src/main/res/drawable/ic_warning.xml
  app/src/main/res/drawable/rectangle_solid_white_12.xml
  app/src/main/res/layout/view_nottodo_snackbar.xml
Labels: enhancement, 준서 🐺

#120 Feat/104 recommendation complete
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/nottodo/data/remote/api/ApiFactory.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/RecommendActionListService.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/RecommendMissionListService.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/RecommendationActionListService.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/RecommendationMainListService.kt
  app/src/main/java/kr/co/nottodo/data/remote/interceptor/TokenInterceptor.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/FailureResponseDto.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/RecentMissionListDto.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/RecommendationActionListDTO.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/RecommendationMainListDTO.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/recommendation/action/RecommendActionListDTO.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/recommendation/mission/RecommendMissionListDto.kt
  app/src/main/java/kr/co/nottodo/presentation/addition/adapter/MissionHistoryAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/addition/view/AdditionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/addition/viewmodel/AdditionViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/HomeFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/login/view/LoginActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/modification/viewmodel/ModificationViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/action/RecommendationActionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/action/RecommendationActionListAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/action/adapter/RecommendActionAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/action/view/RecommendActionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/action/viewmodel/RecommendActionViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/main/RecommendationMain.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/main/RecommendationMainActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/main/RecommendationMainListViewAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/mission/adapter/RecommendMissionAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/mission/view/RecommendMissionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/mission/viewmodel/RecommendMissionViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/model/RecommendMissionActionUiModel.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/model/RecommendMissionUiModel.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/viewmodel/RecommendationViewModel.kt
  app/src/main/java/kr/co/nottodo/util/ThrowableExtension.kt
  app/src/main/res/drawable/ic_destroy.xml
  app/src/main/res/drawable/ic_recommendation_action_info.xml
  app/src/main/res/drawable/rectangle_selector_item_recommend_action.xml
  app/src/main/res/layout/activity_recommend_action.xml
  app/src/main/res/layout/activity_recommend_mission.xml
  app/src/main/res/layout/activity_recommendation_action_title.xml
  app/src/main/res/layout/fragment_recommendation_action_select.xml
  app/src/main/res/layout/item_recommend_action.xml
  app/src/main/res/layout/item_recommend_mission.xml
  app/src/main/res/layout/item_recommendation_action_category.xml
  app/src/main/res/layout/item_recommendation_action_select.xml
  app/src/main/res/layout/item_recommendation_action_title.xml
  app/src/main/res/layout/item_recommendation_main.xml
  app/src/main/res/values/typography.xml
Labels: enhancement, 준서 🐺

#128 Feat/119 login add
  app/src/main/java/kr/co/nottodo/presentation/login/view/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 준서 🐺

#130 Feat/117 edit onboard 2
  app/src/main/java/kr/co/nottodo/presentation/onboard/OnboardInterface.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/OnboardActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/OnboardSecondFragment.kt
  app/src/main/res/layout/fragment_onboard_second.xml
  app/src/main/res/raw/lottie_onboard_second.json
  app/src/main/res/raw/video_logo_onboard_two.mp4
  app/src/main/res/values/strings.xml
Labels: enhancement, 준서 🐺

#133 Fix/54 home inflate
  app/src/main/java/kr/co/nottodo/Application.kt
  app/src/main/java/kr/co/nottodo/MainActivity.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/home/HomeService.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/home/HomeDoAnotherDay.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/home/getHomeDoAnotherDay.kt
  app/src/main/java/kr/co/nottodo/presentation/achieve/AchieveFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/addition/adapter/MissionHistoryAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/addition/view/AdditionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/addition/viewmodel/AdditionViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/DialogCloseListener.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/HomeAdpater.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/HomeBottomCalenderViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/HomeDoAnotherFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/HomeFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/HomeMenuBottomSheetFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/HomeNottodoDeleteFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/HomeViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/login/view/LoginActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/modification/view/ModificationActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/modification/viewmodel/ModificationViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/mypage/view/MyPageInformationActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/OnboardActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/onboard/view/OnboardFirstFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/action/adapter/RecommendActionAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/action/view/RecommendActionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/mission/adapter/RecommendMissionAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/mission/view/RecommendMissionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/util/ActivityExtension.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/util/ContextExtension.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/util/DiffUtilItemCallback.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/util/FlexboxExtension.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/util/IntentExtension.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/util/ListExtension.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/util/NotTodoDebugTree.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/util/ThrowableExtension.kt
  app/src/main/java/kr/co/nottodo/util/DialogCloseListener.kt
  app/src/main/java/kr/co/nottodo/view/calendar/weekly/WeeklyCalendarView.kt
  app/src/main/res/drawable/ic_image_bin.xml
  app/src/main/res/layout/fragment_home_do_another.xml
  app/src/main/res/layout/fragment_home_menu_bottom_sheet.xml
  app/src/main/res/layout/fragment_not_todo_delete_dialog.xml
  app/src/main/res/layout/fragment_onboard_first.xml
  app/src/main/res/layout/item_list_home_todo.xml
  app/src/main/res/values/strings.xml
Labels: 윤정 🐱

#136 Feat/134 modification touch padding
  app/src/main/java/kr/co/nottodo/data/remote/model/modification/ModificationDto.kt
  app/src/main/java/kr/co/nottodo/presentation/modification/view/ModificationActivity.kt
  app/src/main/res/layout/activity_addition.xml
  app/src/main/res/layout/activity_modification.xml
Labels: enhancement, 준서 🐺

#142 Feat/141 qa 2 junseo
  app/src/main/java/kr/co/nottodo/presentation/modification/view/ModificationActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/mypage/view/MyPageLogoutDialogFragment.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, 준서 🐺

#146 [feat]#143 Property가 있는 Event Tracking 함수 추가
  app/src/main/java/kr/co/nottodo/util/Amplitude.kt
Labels: enhancement, 준서 🐺

#148 [feat]#143 trackingSessionEvents 꺼서 Start Session, End Session 보내지 않게 하기
  app/src/main/java/kr/co/nottodo/util/NotTodoAmplitude.kt
Labels: enhancement, 준서 🐺

#153 Feat/152 writing washing junseo
  app/src/main/java/kr/co/nottodo/presentation/addition/view/AdditionActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/modification/model/NotTodoData.kt
  app/src/main/java/kr/co/nottodo/presentation/modification/view/ModificationActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/modification/viewmodel/ModificationViewModel.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/mission/adapter/RecommendMissionAdapter.kt
  app/src/main/java/kr/co/nottodo/presentation/recommendation/mission/view/RecommendMissionActivity.kt
  app/src/main/res/layout/activity_addition.xml
  app/src/main/res/layout/activity_modification.xml
  app/src/main/res/layout/activity_recommend_action.xml
  app/src/main/res/layout/activity_recommend_mission.xml
  app/src/main/res/layout/item_recommend_action.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 준서 🐺

#157 Feat/155 app name logo
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_foreground.png
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi-v33/ic_launcher.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, 준서 🐺

#161 Feat/160 release를 위한 작업
  .gitignore
  app/build.gradle
  app/src/main/java/kr/co/nottodo/service/FirebaseMessagingService.kt
Labels: enhancement, 준서 🐺, 윤정 🐱, 훈기 🐻, 민영 🐰

#164 Fix/162 final ui update
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: enhancement, 준서 🐺

#163 [chore]#160 앱 버전 코드 2로 수정
  app/build.gradle
Labels: enhancement, 준서 🐺, 윤정 🐱, 훈기 🐻, 민영 🐰

#166 Fix/165 action number erase
  app/build.gradle
  app/src/main/res/values/strings.xml
Labels: bug, 준서 🐺
