Repository DO-NOTTO-DO/AOS-NOTTODO, pull requests merged in 2023-03, with the labels that each got.

#18 Feature/16 kakao login
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/nottodo/Application.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/ApiFactory.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/TokenInterceptor.kt
  app/src/main/java/kr/co/nottodo/data/remote/api/TokenService.kt
  app/src/main/java/kr/co/nottodo/data/remote/model/TokenDto.kt
  app/src/main/java/kr/co/nottodo/presentation/login/view/LoginActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/login/viewmodel/LoginViewModel.kt
Labels: enhancement, 준서 🐺

#22 Feature/12 home layout
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/nottodo/data/Test.kt
  app/src/main/java/kr/co/nottodo/data/model/ResponseHomeDaily.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/HomeAdpater.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/HomeFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/HomeMenuBottomSheetFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/HomeViewModel.kt
  app/src/main/java/kr/co/nottodo/util/DiffUtilItemCallback.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/home_todo_selector.xml
  app/src/main/res/drawable/ic_cancel_grey.xml
  app/src/main/res/drawable/ic_home_label_statistics.xml
  app/src/main/res/drawable/ic_home_plus_btn.xml
  app/src/main/res/drawable/ic_home_todo_active.xml
  app/src/main/res/drawable/ic_home_todo_inactive.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_meatball.xml
  app/src/main/res/drawable/ic_right_stroke.xml
  app/src/main/res/drawable/img_home_logo.xml
  app/src/main/res/drawable/rectangle_border_bg_50.xml
  app/src/main/res/drawable/rectangle_border_black_50.xml
  app/src/main/res/drawable/rectangle_border_grey4_10.xml
  app/src/main/res/drawable/rectangle_border_white_10.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_menu_bottom_sheet.xml
  app/src/main/res/layout/item_list_home_todo.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 윤정 🐱

#25 Feature/23 achieve
  app/src/main/java/kr/co/nottodo/MainActivity.kt
  app/src/main/java/kr/co/nottodo/presentation/achieve/AchieveFragment.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/HomeAdpater.kt
  app/src/main/java/kr/co/nottodo/presentation/home/view/HomeFragment.kt
  app/src/main/res/drawable/ic_achieve_total.9.png
  app/src/main/res/drawable/ic_achieve_total_triangle.xml
  app/src/main/res/layout/fragment_achieve.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/values/strings.xml
Labels: documentation, 윤정 🐱
